// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = 'https://cghwldxpewjcyjgfkhai.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnaHdsZHhwZXdqY2p5Z2ZraGFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4OTgwODQsImV4cCI6MjA4NTQ3NDA4NH0.ALtORnoizP-j7ByrRBkd2yUzEuSKVAbd288xhDOVsi4';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
